spring.application.name=Proj-07_relationship_between_Student_and_University

# University Properties

university.name=Harvard University
university.location=Cambridge
university.ranking=3

# Student Properties

student.name=Ajit Kumar
student.age=23
student.major=Computer Science
student.year=Junior
