spring.application.name=Proj-08-EmployeeManagementSystem

#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=Batch46
#spring.datasource.password=root

#MYSQL JBDC Info
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url= jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=root