#Hotel Info

guest.hotelName=Grand Palace
guest.location=Jaipur

guest.guestId=501
guest.guestName=Vikas Mehta

# Array: Room numbers previously stayed
guest.pastRooms=101,205,310

# List: Requested services
guest.services=Room Cleaning,Breakfast,Laundry,Spa

# Set: Preferences
guest.preferences=Non-Smoking,High Floor,King Bed

# Map: Visit history (year \u2192 number of stays)
guest.history.2021=2
guest.history.2022=4
guest.history.2023=3
