# -------------------------
# DEV PROFILE (H2 Database)
# -------------------------
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.username=batch46
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

# Show SQL in console
spring.jpa.show-sql=true
spring.h2.console.enabled=true

profile.name=dev
